### PR TITLE
type: Verification form for fundees feat:First nine pages

### PR DESCRIPTION
**Pull request by Gbolade-True**
The verification form has 15 pages and was slit between me and @Babscode. 
This is a PR for the first nine pages.

### CODE REVIEW

**Comment by Gbolade-True** [comment]
Here's a link to the deployed version on netlify...
https://elegant-darwin-e70ad0.netlify.app

**Comment by olucheye** [comment]
Change the loading icon color... 
image

**Comment by Gbolade-True** [comment]
> Change the loading icon color...
> image

@olucheye Loading icon color changed

**Comment by olucheye** [comment]
Font - not actual
loading  bar Still missing #FB3F5C

**Comment by seunbayo** [comment]
Fix the above and also add link to your user story

**Pull request closed without merging**
