### PR TITLE
feat:created payment success modal

### PR DESCRIPTION
**Pull request by michealadim**
Created the Payment success modal (responsive). Same page style-sheet and script with hosted image(cloudinary)

### CODE REVIEW

**Comment by seunbayo** [comment]
Please the link to your user profile 

Add link to a hosted version

**Comment by michealadim** [comment]
Okay. Would do shortly.

**Comment by michealadim** [comment]
Hosted Link (Click on Success Payment) : https://priceless-aryabhata-75d1b0.netlify.app/

Clubhouse Story Link: https://app.clubhouse.io/startng/story/47589/payment-success-modal

**Comment by seunbayo** [comment]
Nav bar and menu bar is missing,any reason?

**Comment by michealadim** [comment]
I worked only on the payment modal because the NavBar is in a different ticket that is accrued to another developer. I would implement it once the developer is done since it has to be uniform across all pages. This is same for the footer.

**Comment by seunbayo** [comment]
i will merge the page but you must add the nav bar when it is ready.

**Comment by michealadim** [comment]
Yes, I would sir

**Pull request merged**
