### PR TITLE
43600 - Fundee Dashboard Page

### PR DESCRIPTION
**Pull request by Adiomojeed**

### CODE REVIEW

**Comment by onyijne** [comment]
Okay, please wait for review from @seunbayo

**Comment by seunbayo** [comment]
Please add a live link and your clubhouse story link

**Comment by Adiomojeed** [comment]
FML-Desktop
FML-Mobile
These are the images

**Comment by Adiomojeed** [comment]
Ok, I'll do that soon

**Comment by Adiomojeed** [comment]
https://fundmylaptop.netlify.app/fundee-dashboard
https://app.clubhouse.io/startng/story/43600

**Comment by Adiomojeed** [comment]
@seunbayo

**Comment by seunbayo** [comment]
please check the design and make correctons.

what i am seeing on the design is different from this

**Pull request closed without merging**
