### PR TITLE
public investment

### PR DESCRIPTION
**Pull request by adexdsamson**
A public investment page as designed

### CODE REVIEW

**Comment by adexdsamson** [comment]
https://public-investment.netlify.app
https://res.cloudinary.com/dymahyzab/image/upload/v1592751708/screenshot-www.figma.com-2020.06.21-15_57_57.png

**Comment by onyijne** [comment]
It doesn't display well yet, use bootstrap 4 classes.

**Comment by adexdsamson** [comment]
Okay

**Comment by adexdsamson** [comment]
Okay

**Pull request closed without merging**
