### PR TITLE
fix: made review changes to profile page funders (desktop)

### PR DESCRIPTION
**Pull request by temofedev**
Figma Design:
figma design

My Implemented Design:
funders-profile-page

Hosted URL:
https://temofedev.github.io/user-profile-page-for-funders/

Clubhouse link:
https://app.clubhouse.io/startng/story/43581implement-profile-page-for-funders#

### CODE REVIEW

**Comment by Nwachi** [comment]
Change the slack username. You have the wrong person

**Comment by temofedev** [comment]
I don't understand, the wrong person? How?

**Comment by temofedev** [comment]
Oh! My bad, sorry for mentioning...

I also bear Nwachi....and that's my username on the slack platform of the organization I belong at the moment..

Sorry for the mix ups 😋

**Comment by olucheye** [comment]
Task has been submitted by another person!
Please make a fresh pull of the codebase

**Comment by temofedev** [comment]
Hi @olucheye
There are two tickets with the same design.
One for funders, one for fundees.
Mine is for funders : Implement profile page for funders 43581

**Pull request closed without merging**
